import * as admin from "firebase-admin";
import JSZip from "jszip";
import { createHash } from "crypto";
import { enqueueNotification } from "./notify_trigger";

export async function processPackageBuilds(adminApp: typeof admin) {
  const db = adminApp.firestore();

  const queuedPackagesSnap = await db.collection("packages")
    .where("status", "==", "queued")
    .limit(10)
    .get();

  if (queuedPackagesSnap.empty) {
    return;
  }

  for (const doc of queuedPackagesSnap.docs) {
    const pkg = doc.data();
    const packageId = doc.id;
    const caseId = pkg.caseId;
    const partnerId = pkg.partnerId;

    try {
      await doc.ref.update({
        status: "building",
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      const evidencesSnap = await db.collection("evidences")
        .where("caseId", "==", caseId)
        .where("status", "==", "validated")
        .limit(20)
        .get();

      if (evidencesSnap.empty) {
        throw new Error("FAILED_PRECONDITION: validated evidence가 없습니다.");
      }

      const evidenceDocs = evidencesSnap.docs.slice(0, 10);
      const evidenceList: any[] = [];

      let totalBytes = 0;
      for (const eDoc of evidenceDocs) {
        const e = eDoc.data() as any;
        totalBytes += Number(e.sizeBytes || 0);
      }

      if (totalBytes > 50 * 1024 * 1024) {
        throw new Error("FAILED_PRECONDITION: evidence 총합 크기가 너무 큽니다 (50MB 제한).");
      }

      const zip = new JSZip();

      for (const eDoc of evidenceDocs) {
        const e = eDoc.data() as any;
        if (!e.storagePath) {
          throw new Error(`FAILED_PRECONDITION: evidence ${eDoc.id} storagePath 누락`);
        }

        const bucket = adminApp.storage().bucket();
        const file = bucket.file(e.storagePath);
        const [exists] = await file.exists();
        if (!exists) {
          throw new Error(`NOT_FOUND: evidence 파일이 존재하지 않습니다 (${e.storagePath})`);
        }

        const [buf] = await file.download();
        const sha256 = createHash("sha256").update(buf).digest("hex");

        const filename = e.filename || e.fileUrl || `${eDoc.id}`;
        zip.file(`evidences/${eDoc.id}/${filename}`, buf);

        evidenceList.push({
          evidenceId: eDoc.id,
          filename,
          contentType: e.contentType,
          sizeBytes: buf.length,
          sha256,
          storagePath: e.storagePath
        });
      }

      const createdAtIso = new Date().toISOString();
      zip.file("README.txt", "Submission package generated by AgentRegi.\n");
      zip.file("manifest.json", JSON.stringify({
        caseId,
        packageId,
        partnerId,
        createdAt: createdAtIso,
        evidences: evidenceList
      }, null, 2));

      const zipBuf = await zip.generateAsync({
        type: "nodebuffer",
        compression: "DEFLATE",
        compressionOptions: { level: 6 }
      });

      const checksumSha256 = createHash("sha256").update(zipBuf).digest("hex");

      const artifactPath = `artifacts/${partnerId}/${caseId}/${packageId}/submission_package.zip`;
      const bucket = adminApp.storage().bucket();
      const artifactFile = bucket.file(artifactPath);

      await artifactFile.save(zipBuf, {
        contentType: "application/zip",
        metadata: { cacheControl: "private, max-age=0, no-store" },
        resumable: false
      });

      const batch = db.batch();

      batch.update(doc.ref, {
        status: "ready",
        artifactPath,
        checksumSha256,
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      const caseRef = db.collection("cases").doc(caseId);
      batch.update(caseRef, {
        status: "ready",
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      await batch.commit();
      console.log(`[PackageBuilder] Package ${packageId} built successfully.`);
      
      await enqueueNotification(adminApp, { partnerId }, "package.ready", {
        caseId,
        packageId,
        checksumSha256
      });

    } catch (error: any) {
      console.error(`[PackageBuilder] Failed to build package ${packageId}:`, error);
      
      const batch = db.batch();
      
      batch.update(doc.ref, {
        status: "failed",
        error: {
          category: (error.message || "").includes("FAILED_PRECONDITION") ? "FAILED_PRECONDITION" : "BUILD_ERROR",
          message: error.message || String(error)
        },
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      const caseRef = db.collection("cases").doc(caseId);
      batch.update(caseRef, {
        status: "failed",
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      await batch.commit();
    }
  }
}
